---

# Local Users
local_users:
  - name: admin
    privilege: 15
    role: network-admin
    sha512_password: "{{ ansible_password | password_hash('sha512', salt='arista', rounds=5000) }}"
    ssh_key: "{{ lookup('ansible.builtin.file', '~/.ssh/id_ecdsa.pub') }}"

# AAA
aaa_authorization:
  exec:
    default: local

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1
mgmt_interface_vrf: mgmt

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp:
  servers:
    - name: time1.google.com
      iburst: true
      vrf: mgmt
    - name: time2.google.com
      iburst: true
      vrf: mgmt

# Domain/DNS
ip_name_servers:
  - ip_address: 8.8.8.8
    vrf: mgmt
    priority: 0
# dns_domain: avd.lab

# TerminAttr
daemon_terminattr:
  cvaddrs: # For single cluster
    - "{{ lookup('ansible.builtin.env', 'CV_TATTR_ADDR', default='1.2.3.4:443') }}"
  cvauth:
    method: token-secure
    token_file: "/mnt/flash/cv-onboarding-token"
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  cvvrf: mgmt
  disable_aaa: true

# Point to Point Links MTU Override for Lab
p2p_uplinks_mtu: 9200

# Set IPv4 Underlay Routing and EVPN Overlay Routing to use eBGP
underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp
#underlay_rfc5549: true

# Configure password authentication for BGP peerings
# bgp_peer_groups:
#   evpn_overlay_peers:
#     password: "Q4fqtbqcZ7oQuKfuWtNGRQ=="
#   ipv4_underlay_peers:
#     password: "7x4B4rnJhZB438m9+BrBfQ=="
#   mlag_ipv4_underlay_peer:
#     password: "4b21pAdCvWeAqpcKDFMdWw=="

# # L3 Edge port definitions. This can be any port in the entire Fabric, where IP interfaces are defined.
l3_edge:
  # Define a new IP pool that will be used to assign IP addresses to L3 Edge interfaces.
  p2p_links_ip_pools:
    - name: S1_to_S2_IP_pool
      ipv4_pool: 172.16.255.0/24
  # Define a new link profile which will match the IP pool, the used ASNs and include the defined interface into underlay routing
  p2p_links_profiles:
    - name: S1_to_S2_profile
      ip_pool: S1_to_S2_IP_pool
      as: [ 65103, 65203 ]
      include_in_underlay_protocol: true
  # Define each P2P L3 link and link the nodes, the interfaces and the profile used.
  p2p_links:
    - id: 1
      nodes: [ s1-brdr1, s2-brdr1 ]
      interfaces: [ Ethernet55/1, Ethernet55/1 ]
      profile: S1_to_S2_profile
    - id: 2
      nodes: [ s1-brdr2, s2-brdr2 ]
      interfaces: [ Ethernet55/1, Ethernet55/1 ]
      profile: S1_to_S2_profile

# # CloudVision Topology Tags
generate_cv_tags:
  topology_hints: true

network_ports:
# Shut down unused ports based on the switch name (regex) and the target platform. 
# If the network_ports model is used to configure downlink ports, this must be the first entry in the list. 
# If downlinks are defined in connected_endpoints data mode, the connected_endpoints configuration takes precedence.
  - switches:
      - .*-leaf.*
    platforms:
      - 7050SX3
    switch_ports:
      - Ethernet1-48
    enabled: false
    description: UNUSED

load_interval:
  # Default load interval in seconds.
  default: 1

# Flow-tracking configuration
# Default enabling of flow-tracking(IPFIX) for various interface types across the fabric.
# Flow Tracking can also be enabled/disabled under each of the specific data models.
# For general flow-tracking settings see `flow_tracking_settings`.
fabric_flow_tracking:
  # Enable flow-tracking on all fabric uplinks.
  uplinks:
    enabled: true

  # Enable flow-tracking on all fabric downlinks.
  downlinks:
    enabled: true

  # Enable flow-tracking on all endpoints ports.
  endpoints:
    enabled: true

  # Enable flow-tracking on all p2p_links defined under l3_edge.
  l3_edge:
    enabled: true

  # Enable flow-tracking on all MLAG peer interfaces.
  mlag_interfaces:
    enabled: true

  # Enable flow-tracking on all node.l3_interfaces and network-services tenants.vrfs.l3_interfaces.
  l3_interfaces:
    enabled: true

  # Enable flow-tracking on all node.l3_port_channels.
  l3_port_channels:
    enabled: true

flow_tracking_settings:
  # The options relevant only for flow tracker type sampled.
  sampled:
    encapsulation:
      ipv4_ipv6: true
      mpls: false
    sample: 5000
  trackers:
  - exporters:
    - collectors:
      - host: 127.0.0.1
      local_interface: Loopback0
      name: CV-TELEMETRY
      template_interval: 3600000
    name: FLOW-TRACKER
    record_export:
      on_inactive_timeout: 70000
      on_interval: 30000 # export records every 30,000ms (30s)
