---
custom_structured_configuration_prefix: ['csc_']

# AAA settings
aaa_settings:
  authorization:
    exec:
      default: local
  local_users:
    - name: admin
      privilege: 15
      role: network-admin
      sha512_password: "{{ ansible_password | password_hash('sha512', salt='arista', rounds=5000) }}"
      ssh_key: "{{ lookup('ansible.builtin.file', '~/.ssh/id_ecdsa.pub') }}"

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1
mgmt_interface_vrf: mgmt

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp_settings:
  servers:
    - name: time1.google.com
      iburst: true
    - name: time2.google.com
      iburst: true

# Domain/DNS
dns_settings:
  servers:
    - ip_address: 8.8.8.8
      vrf: mgmt
      priority: 0

# TerminAttr
cv_settings:
  cvaas:
    enabled: "{{ True if lookup('ansible.builtin.env', 'CV_CLOUD') else False }}"
    clusters:
      - name: cvaas
        region: "{{ lookup('ansible.builtin.env', 'CV_CLOUD_REGION', default='staging') }}"
        token_file: "/mnt/flash/cv-onboarding-token"
  terminattr:
    ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
    smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
    disable_aaa: true

# Point to Point Links MTU Override for Lab
p2p_uplinks_mtu: 9200

# Set IPv4 Underlay Routing and EVPN Overlay Routing to use eBGP
underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp
#underlay_rfc5549: true

# Configure password authentication for BGP peerings
# bgp_peer_groups:
#   evpn_overlay_peers:
#     password: "Q4fqtbqcZ7oQuKfuWtNGRQ=="
#   ipv4_underlay_peers:
#     password: "7x4B4rnJhZB438m9+BrBfQ=="
#   mlag_ipv4_underlay_peer:
#     password: "4b21pAdCvWeAqpcKDFMdWw=="

network_ports:
# Shut down unused ports based on the switch name (regex) and the target platform. 
# If the network_ports model is used to configure downlink ports, this must be the first entry in the list. 
# If downlinks are defined in connected_endpoints data mode, the connected_endpoints configuration takes precedence.
  - switches:
      - .*-leaf.*
    platforms:
      - 7050SX3
    switch_ports:
      - Ethernet1-48
    enabled: false
    description: UNUSED

load_interval:
  # Default load interval in seconds.
  default: 1

# Flow-tracking configuration
# Default enabling of flow-tracking(IPFIX) for various interface types across the fabric.
# Flow Tracking can also be enabled/disabled under each of the specific data models.
# For general flow-tracking settings see `flow_tracking_settings`.
fabric_flow_tracking:
  uplinks:
    enabled: true
  downlinks:
    enabled: true
  endpoints:
    enabled: true
  l3_edge:
    enabled: true
  mlag_interfaces:
    enabled: true
  l3_interfaces:
    enabled: true
  l3_port_channels:
    enabled: true

flow_tracking_settings:
  # The options relevant only for flow tracker type sampled.
  sampled:
    encapsulation:
      ipv4_ipv6: true
      mpls: false
    sample: 5000
  trackers:
  - exporters:
    - collectors:
      - host: 127.0.0.1
      local_interface: Loopback0
      name: CV-TELEMETRY
      template_interval: 3600000
    name: FLOW-TRACKER
    record_export:
      on_inactive_timeout: 70000
      on_interval: 30000 # export records every 30,000ms (30s)

bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

bgp_peer_groups:
  ipv4_underlay_peers:
    bfd: true