! Command: show running-config
! device: s1-brdr2 (cEOSLab, EOS-4.36.0.1F-47417197.43601F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$VMQurCeojY9yg9Xa$CiOcLSn3EUjQxaRwi5PKvQYYhOlGmk17avGVxu46y3jYqHouDInHaVNQJY.xUb.ma15oph1eGKvFhDkps7m/A/
!
management api http-commands
   no shutdown
   !
   vrf mgmt
      no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname s1-brdr2
ip name-server vrf mgmt 8.8.8.8
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
vrf instance mgmt
!
management api gnmi
   transport grpc default
      vrf mgmt
!
management api netconf
   transport ssh default
      vrf mgmt
!
interface Ethernet49/1
!
interface Ethernet50/1
!
interface Ethernet51/1
!
interface Ethernet52/1
!
interface Ethernet55/1
!
interface Management1
   description oob_management
   vrf mgmt
   ip address 192.168.0.101/24
   no lldp transmit
   no lldp receive
!
ip routing
no ip routing vrf mgmt
!
ip route vrf mgmt 0.0.0.0/0 192.168.0.1
!
ntp local-interface vrf mgmt Management1
ntp server vrf mgmt 0.pool.ntp.org prefer
!
end