{
 "title": "AVD Network",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(system_processes_process_state_cpu_usage_system{job=\"eos_gnmi\"},site)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(system_processes_process_state_cpu_usage_system{job=\"eos_gnmi\"},pod)"
    }
   },
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(system_processes_process_state_cpu_usage_system{job=\"eos_gnmi\"},role)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "S1: BGP Session State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_state_session_state{site=\"s1\",session_state=\"ESTABLISHED\"}) by (session_state,source)",
     "legendFormat": "{{source}}: {{session_state}}"
    },
    {
     "expr": "sum(network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_state_session_state{site=\"s1\",session_state!=\"ESTABLISHED\"}) by (session_state,source)",
     "legendFormat": "{{source}}: {{session_state}}"
    }
   ]
  },
  {
   "title": "S2: BGP Session State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_state_session_state{site=\"s2\",session_state=\"ESTABLISHED\"}) by (session_state,source)",
     "legendFormat": "{{source}}: {{session_state}}"
    },
    {
     "expr": "sum(network_instances_network_instance_protocols_protocol_bgp_neighbors_neighbor_state_session_state{site=\"s2\",session_state!=\"ESTABLISHED\"}) by (session_state,source)",
     "legendFormat": "{{source}}: {{session_state}}"
    }
   ]
  },
  { "title": "DCI Switches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "S1 DCI Interface Rate bits/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(interfaces_interface_state_counters_in_octets{job=\"eos_gnmi\", interface_name!=\"Management1\", source=~\"s1-brdr1|s1-brdr2\"}[1m]) * 8",
     "legendFormat": "{{source}}: {{interface_name}} RX"
    },
    {
     "expr": "irate(interfaces_interface_state_counters_out_octets{job=\"eos_gnmi\", interface_name!=\"Management1\", source=~\"s1-brdr1|s1-brdr2\"}[1m]) * 8",
     "legendFormat": "{{source}}: {{interface_name}} TX"
    }
   ]
  },
  {
   "title": "S2 DCI Interface Rate bits/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(interfaces_interface_state_counters_in_octets{job=\"eos_gnmi\", interface_name!=\"Management1\", source=~\"s2-brdr1|s2-brdr2\"}[1m]) * 8",
     "legendFormat": "{{source}}: {{interface_name}} RX"
    },
    {
     "expr": "irate(interfaces_interface_state_counters_out_octets{job=\"eos_gnmi\", interface_name!=\"Management1\", source=~\"s2-brdr1|s2-brdr2\"}[1m]) * 8",
     "legendFormat": "{{source}}: {{interface_name}} TX"
    }
   ]
  },
  { "title": "Spine Switches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Spine 1 Interface Rate bits/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(interfaces_interface_state_counters_in_octets{job=\"eos_gnmi\", role=\"spine\", interface_name!=\"Management1\", source=~\".*-spine1\"}[1m]) * 8",
     "legendFormat": "{{source}}: {{interface_name}} RX"
    },
    {
     "expr": "irate(interfaces_interface_state_counters_out_octets{job=\"eos_gnmi\", role=\"spine\", interface_name!=\"Management1\", source=~\".*-spine1\"}[1m]) * 8",
     "legendFormat": "{{source}}: {{interface_name}} TX"
    }
   ]
  },
  {
   "title": "Spine 2 Interface Rate bits/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(interfaces_interface_state_counters_in_octets{job=\"eos_gnmi\", role=\"spine\", interface_name!=\"Management1\", source=~\".*-spine2\"}[1m]) * 8",
     "legendFormat": "{{source}}: {{interface_name}} RX"
    },
    {
     "expr": "irate(interfaces_interface_state_counters_out_octets{job=\"eos_gnmi\", role=\"spine\", interface_name!=\"Management1\", source=~\".*-spine2\"}[1m]) * 8",
     "legendFormat": "{{source}}: {{interface_name}} TX"
    }
   ]
  }
 ]
}