[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = "telegraf-collector"
  omit_hostname = false

# Expose Telegraf metrics to be scraped by Prometheus
[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"
  #string_as_label = true

[[outputs.loki]]
  domain = "http://loki:3100"
  sanitize_label_names = true

# Collect streaming telemetry via gNMI from Arista cEOS
[[inputs.gnmi]]
  ## List of cEOS addresses to target (Default gNMI port is often 50051 or 6030)
  addresses = ["s1-spine1:6030", "s1-spine2:6030", "s1-leaf1:6030", "s1-leaf2:6030", "s1-leaf3:6030",
  "s1-leaf4:6030", "s1-brdr1:6030", "s1-brdr2:6030", "s2-spine1:6030", "s2-spine2:6030", "s2-leaf1:6030", "s2-leaf2:6030", "s2-leaf3:6030", 
  "s2-leaf4:6030", "s2-brdr1:6030", "s2-brdr2:6030"]
  
  ## Credentials for the switch
  username = "admin"
  password = "admin"
  
  encoding = "json"
  redial = "10s"
  path_guessing_strategy = "subscription"

  ## Define subscriptions for OpenConfig interface metrics
  [[inputs.gnmi.subscription]]
    name = "bgp_state"
    origin = "openconfig"
    path = "/openconfig-network-instance:network-instances/network-instance[name=default]/protocols/protocol/bgp/neighbors/neighbor/state/session-state"
    subscription_mode = "sample"
    sample_interval = "5s"

  [[inputs.gnmi.subscription]]
    name = "bgp_messages"
    origin = "openconfig"
    path = "/openconfig-network-instance:network-instances/network-instance[name=default]/protocols/protocol/bgp/neighbors/neighbor/state/messages"
    subscription_mode = "sample"
    sample_interval = "5s"